# Generated by Django 5.0.4 on 2024-05-08 06:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0003_alter_mebel_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mebel',
            options={'ordering': ['price'], 'verbose_name': 'мебель', 'verbose_name_plural': 'мебель'},
        ),
        migrations.AddField(
            model_name='mebel',
            name='parse_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mebel',
            name='link',
            field=models.TextField(verbose_name='Cсылка'),
        ),
    ]
