# Generated by Django 5.0.4 on 2024-05-08 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0004_alter_mebel_options_mebel_parse_datetime_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mebel',
            options={'ordering': ['parse_datetime', 'price'], 'verbose_name': 'мебель', 'verbose_name_plural': 'мебель'},
        ),
    ]
